### ISSUE TITLE
White screen after flashing firmware

### ISSUE THREAD

**Issue by Gamemaster2022** [metroid-maniac/SCFW#1]
Hello, I downloaded your custom firmware and put it on my SD card as said in the description. Then I tried the kernel.gba - it worked I got into the menu. I liked the new menu so I decided to go ahead and flash the cartridge with the firmware.frm. Everything finished successfuly but after restart I got only white screen and nothing else. I am worried I bricked it. Any suggestions what to do now? 

Help is greatly appreciated.

Thanks a lot

**Comment by metroid-maniac** [comment]
Hi.

Could you describe what happens when you try to use the cart? Do you see the Game Boy logo and a normal Nintendo logo before going to the white screen?

If you have a Nintendo DS and a DS flashcart, there are a few ways to unbrick the cart. You can try running flashmp or scflash_sd.  If your DS flashcart runs YSMenu or TwilightMenu++, you can also run sd_v185 natively to use the official firmware updater too.
[flashmp.zip](https://github.com/metroid-maniac/SCFW/files/14723755/flashmp.zip)
[sd_v185.zip](https://github.com/metroid-maniac/SCFW/files/14723756/sd_v185.zip)
[SCflash_sd.zip](https://github.com/metroid-maniac/SCFW/files/14723757/SCflash_sd.zip)

**Comment by Gamemaster2022** [comment]
> Hi.
> 
> Could you describe what happens when you try to use the cart? Do you see the Game Boy logo and a normal Nintendo logo before going to the white screen?
> 
> If you have a Nintendo DS and a DS flashcart, there are a few ways to unbrick the cart. You can try running flashmp or scflash_sd. If your DS flashcart runs YSMenu or TwilightMenu++, you can also run sd_v185 natively to use the official firmware updater too. [flashmp.zip](https://github.com/metroid-maniac/SCFW/files/14723755/flashmp.zip) [sd_v185.zip](https://github.com/metroid-maniac/SCFW/files/14723756/sd_v185.zip) [SCflash_sd.zip](https://github.com/metroid-maniac/SCFW/files/14723757/SCflash_sd.zip)

Thanks for quick reply,
basically I just insert the cart in with my pre-formatted 2GB SD. GAME BOY logo with Nintendo appears and then it shifts into pure white screen (see attached photos). I unfortuanetly don't own a DS so that will be a problem

![IMG_20240322_145631_766](https://github.com/metroid-maniac/SCFW/assets/76746814/f41b2069-f1dc-498c-840b-f9768f7644c2)

![IMG_20240322_145645_763](https://github.com/metroid-maniac/SCFW/assets/76746814/782b1d79-4d95-402b-a15c-aadd012d2443)

**Comment by Gamemaster2022** [comment]
Is there any way to unbrick it without DS?

**Comment by metroid-maniac** [comment]
Do you have any other GBA flashcarts?

**Comment by Gamemaster2022** [comment]
> Do you have any other GBA flashcarts?

I have only Evedrive GB X5 that doesn't run any GBA stuff as it's GB/GBC only

**Comment by Gamemaster2022** [comment]
Well, I ended up ordering a new cartridge. Lesson learnt - Do not flash the firmware when it's not necessary. I plan on getting a DS so I'll fix the cart too the way you mentioned. The CFW is very nice and when the other one arrives I'll definitely use it again. Keep up the great work. I'm closing this issue as resolved
