### ISSUE TITLE
SDRAM write failed at

### ISSUE THREAD

**Issue by pitrako** [metroid-maniac/SCFW#13]
I get this message repeatedly sometimes when turning off and turning on, but If I let the console off a few seconds and turn on It goes away and saves correctly.

**Comment by OmDRetro** [comment]
Issue sounds [similar to this bug](https://github.com/metroid-maniac/SCFW/issues/6).

- Can you detail the steps you took to get this error? Did you play with your GBA switch?
- Please indicate the console you're using(GBA/SP/Micro/NDS/NDSL). Are you using a clone like an EXEQ Game Box or Revo K101?

**Comment by pitrako** [comment]
My gba sp is AGS-001, I just touch the power switch only once each time for turning off and on:
1-Start console and start game.
2-Turn off console.
3-Inmediately turn on console again:
![IMG_20240709_101021](https://github.com/metroid-maniac/SCFW/assets/42267151/1ae3a6c0-b81f-4d34-9642-ccae3c280608)
4-Turn off console again.
5-Wait a few seconds.
6-Turn on console.
7-SCFW says is creating the save for the game.
8-Everything is normal until it happens again.

**Comment by OmDRetro** [comment]
After some searching across the net, looks like there's a way to figure out if the battery cell(coin battery) has gone dry. That error indicates a dry battery based on what I found. Since the stock firmware has an SDRAM test feature on it, it actually tells you whether or not it's working as intended and a user was able to fix it by swapping out the dry battery cell with a new one.

[Reference here](https://gbatemp.net/threads/supercard-sd-micro-sd-gba-sdram-error.554029/post-9847150)

# `Solution: Try swapping out the CR2032 battery in your SuperCard SD with a new one and see if it works for you`

**Comment by pitrako** [comment]
sdram is ok but flash id gives me error:
![IMG_20240709_215730](https://github.com/metroid-maniac/SCFW/assets/42267151/30e9db7c-10f3-418b-94a8-00e2943edf5e)
![IMG_20240709_215750](https://github.com/metroid-maniac/SCFW/assets/42267151/edad5dc6-63ed-4fb8-9bbe-cd13e6d32eb3)
![IMG_20240709_215819](https://github.com/metroid-maniac/SCFW/assets/42267151/158ef85a-215d-4b54-b2d0-d855fc41ed01)
![IMG_20240709_215838](https://github.com/metroid-maniac/SCFW/assets/42267151/3203a520-e272-4005-9462-5337ef08afe8)
![IMG_20240709_215903](https://github.com/metroid-maniac/SCFW/assets/42267151/3e234ae4-770e-48a1-9084-01debf199c41)

**Comment by OmDRetro** [comment]
- OS: SuperCard SD version 1.52

### Why are you booting SCFW from this version?
Based on the error you shown, the `OFW version 1.52 doesn't recognize your flash chip and that's probably causing some of the problems here`. 

The tests I do is to boot from OFW 1.85 to SCFW and I've not experienced any issue so far.
Also, have you tested if your coin battery has gone dry?

**Comment by pitrako** [comment]
Now with 1.85 I get different sdram errors, flash id is the same error I think, I am going to test another battery but I don't know when, thanks:
![IMG_20240710_181247](https://github.com/metroid-maniac/SCFW/assets/42267151/12697e90-9d79-4c60-be65-5076030216c0)
![IMG_20240710_181310](https://github.com/metroid-maniac/SCFW/assets/42267151/77862ca3-78e0-42ac-8441-c1f6da6e1a26)
![IMG_20240710_181554](https://github.com/metroid-maniac/SCFW/assets/42267151/b071f6cb-5ed9-411a-8fa0-c549d0f945e4)
![IMG_20240710_181723](https://github.com/metroid-maniac/SCFW/assets/42267151/e41e7e40-2aeb-43ae-8ea0-8eb9ac34696a)

**Comment by OmDRetro** [comment]
Hm... Alright, but `since this issue is similar to another that I referenced and that both stock firmware(v1.85) and SCFW show the same problem` (SDRAM write failed).

## This is more likely tied to the edge connectors of the GBA SP not having proper contacts with the SuperCard SD pins.

### Try this first:
* Clean the pins of the SuperCard SD (use either high concentrate `IPA / Isopropyl Alcohol` or Acetone[Be EXTRA careful with this one or better yet acetone-free nail polish removers will do] )
   * DO NOT USE WATER TO CLEAN THE PINS.
   * Use Q tips (or cotton buds) to absorb the IPA/solvent then rub it on the SuperCard SD pins to clean it
* Alternatively, you can open up/disassemble the SuperCard SD then try wedging in a small piece of paper under the SuperCard SD PCB to slightly elevate the board. Reassemble the cartridge then slot it in your GBA SP.
* See if that fixes the SDRAM issue for you.

**Comment by pitrako** [comment]
The pins are clean, I think is the cartridge that is bad because I have an everdrive clone for gb/gbc games that works ok, close this.

**Comment by OmDRetro** [comment]
Ok, but I'd rather let you know that anything can happen especially during flashing. If the pins aren't properly touching the edge connectors, who knows what the behavior will be when you flash the cartridge?

For now, as you requested, the issue ticket will be closed. Feel free to file anew if this persists.
